language: python
dist: xenial
cache: pip

addons:
  apt:
    update: true
    packages: shellcheck
    
install:
 - pip install -U pip
 - pip install -U flake8
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi

script:
 - for file in $(find . -type f -name \"*.sh\"); do shellcheck --format=gcc $file; done;
 - cd benchmark/data
 - flake8 --statistics --count
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi
