#!/bin/bash
WORKER_LIST="worker.list"
./update.sh
for LINE in $(cat $WORKER_LIST | grep -vE "^#"); do
	WORKERNAME=`echo $LINE | awk -F"/" '{print $NF}'`

	echo "[worker:$WORKERNAME] Updating..."
	ssh $WORKERNAME -o "StrictHostKeyChecking no" "bash -s" < ./update/update.sh

	echo "[worker:$WORKERNAME] Update is completed."
done
