apiVersion: v1
kind: PersistentVolume
metadata:
        name: datadir
        labels:
                kubeless: kafka
spec:
        accessModes:
        - ReadWriteOnce
        capacity:
                storage: 1Gi
        hostPath:
                path: "/root/paprika-k/"
