apiVersion: v1
kind: PersistentVolume
metadata:
        name: zookeeper
        labels:
                kubeless: zookeeper
spec:
        accessModes:
        - ReadWriteOnce
        capacity:
                storage: 1Gi
        hostPath:
                path: "/root/paprika-z/"
